name: ship_watch_adjuster
description: "A maritime watchkeeper tool for calculating bridge duty start times during Clock Advance or Retard events."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration para sa automated icon generation (Isang beses lang dapat ito)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon_apps.png"
  adaptive_icon_background: "#121b29"
  adaptive_icon_foreground: "icon_apps.png"

# Flutter assets settings (Isang beses lang din ito)
flutter:
  uses-material-design: true
  assets:
    - icon_apps.png
